// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81bx-K8K81m8KSmBELOQ4GLzNCp4nu_k',
    appId: '1:11805575717:web:8ba7c2d953b48b0050cdcc',
    messagingSenderId: '11805575717',
    projectId: 'zekrayaty-app',
    authDomain: 'zekrayaty-app.firebaseapp.com',
    storageBucket: 'zekrayaty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnf_spD4EB_0he269Uc8dionQCV5qoE_E',
    appId: '1:11805575717:android:e194e3acad0082a850cdcc',
    messagingSenderId: '11805575717',
    projectId: 'zekrayaty-app',
    storageBucket: 'zekrayaty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDuDsOCqv0370qZuchBdGFAtvXsR23VeE',
    appId: '1:11805575717:ios:282913d8662e4a6450cdcc',
    messagingSenderId: '11805575717',
    projectId: 'zekrayaty-app',
    storageBucket: 'zekrayaty-app.appspot.com',
    iosBundleId: 'com.example.zekrayatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDuDsOCqv0370qZuchBdGFAtvXsR23VeE',
    appId: '1:11805575717:ios:282913d8662e4a6450cdcc',
    messagingSenderId: '11805575717',
    projectId: 'zekrayaty-app',
    storageBucket: 'zekrayaty-app.appspot.com',
    iosBundleId: 'com.example.zekrayatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC81bx-K8K81m8KSmBELOQ4GLzNCp4nu_k',
    appId: '1:11805575717:web:bb4809ea0bc9bc5d50cdcc',
    messagingSenderId: '11805575717',
    projectId: 'zekrayaty-app',
    authDomain: 'zekrayaty-app.firebaseapp.com',
    storageBucket: 'zekrayaty-app.appspot.com',
  );
}
